---
- name: Install and configure Apache Airflow
  hosts: airflow
  become: yes

  tasks:
    - include_role:
        name: airflow
      vars:
        rv_airflow_version: "{{ gv_airflow_version }}"
        rv_mysql_host: "{{ groups.mysl | first }}"
        rv_spark_master_host: "{{ groups.sparkmaster | first }}"
