---
- name: Install and configure Hive metastore (with hadoop binaries)
  hosts: metastore
  become: yes

  tasks:
    - include_role:
        name: os-setup
        
    - include_role:
        name: os-setup
        tasks_from: client_config.yaml

    - include_role:
        name: hadoop
      vars:
        rv_hadoop_version: "{{ gv_hadoop_version }}"

    - include_role:
        name: hive-metastore
      vars:
        rv_metastore_version: "{{ gv_metastore_version }}"
        rv_hadoop_version: "{{ gv_hadoop_version }}"
        rv_mysql_host: "{{ groups.mysql | first }}"