- include_tasks: main.yaml

- name: Stop spark cluster to avoid orphan workers
  ansible.builtin.systemd:
    name: spark
    state: stopped
    enabled: yes
    deamon_reload: true
  ignore_errors: true

- name: Create workers file from template
  ansible.builtin.template:
    src: "workers.j2"
    dest: "{{ rv_spark_config }}/workers"

- name: Create spark.service from template
  ansible.builtin.template:
    src: "spark.service.j2"
    dest: "/etc/systemd/system/spark.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable spark service
  ansible.builtin.systemd:
    name: spark
    state: restarted
    enabled: yes
    domain_reload: true
